# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"}
# ]
question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "JavaScript derives from a later version of Java",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "History",
        "question": "The Kingdom of Prussia briefly held land in Estonia.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "McCree from Overwatch originally started as a character that was going to appear in a scrapped Starcraft game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "King Gizzard &amp; The Lizard Wizard&#039;s album &quot;Nonagon Infinity&quot; can be looped seamlessly.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science &amp; Nature",
        "question": "Male pandas do handstands while urinating on trees. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "History",
        "question": "Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Art",
        "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science &amp; Nature",
        "question": "The Doppler effect applies to light.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Bosnia and Herzegovina is a country located in the Baltic region in Europe.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science &amp; Nature",
        "question": "Albert Einstein won a noble prize for his theory of relativity.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Mythology",
        "question": "In Greek mythology, Hera is the goddess of harvest.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "The United States of America was the first country to launch a man into space.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Politics",
        "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Comics",
        "question": "Deadpool&#039;s identity is Slade Wilson.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Comics",
        "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Politics",
        "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The Sun rises from the North.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In Chobits, Hideki found Chii in his apartment.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "Coca-Cola&#039;s original colour was green.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Television",
        "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The color orange is named after the fruit.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "Peyton Manning retired after winning Super Bowl XLIX.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Slovakia is a member of European Union-",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Codemasters is the developer of the Gran Turismo series.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "Adolf Hitler was tried at the Nuremberg trials.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Music",
        "question": "The band, HEALTH, is called HEALTH because they wanted to choose an everyday word for the band name.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Music",
        "question": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen Beetle in the background.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "The Killer Whale is considered a type of dolphin.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "An Astronomical Unit is the distance between Earth and the Moon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "You are allowed to sell your soul on eBay.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
